# TODO: Double-check yaw parameters. Currently induces weird behavior in sim
[cf2x_L250]
acc_coef = 0.0
cmd_f_coef = 1.0633
rpy_coef = [-286.2, -286.2, -192.9]
rpy_rates_coef = [-23.03, -23.03, -22.22]
cmd_rpy_coef = [225.6, 225.6, 323.5]

# TODO: Check if parameters are correct
[cf2x_P250]
acc_coef = 0.0
cmd_f_coef = 1.0633
rpy_coef = [-99.94, -130.3, 0.0]
rpy_rates_coef = [-13.3, -16.33, 0.0]
cmd_rpy_coef = [84.73, 119.3, 0.0]

# TODO: Check if parameters are correct
[cf2x_T350]
acc_coef = 0.0
cmd_f_coef = 1.0633
rpy_coef = [-99.94, -130.3, 0.0]
rpy_rates_coef = [-13.3, -16.33, 0.0]
cmd_rpy_coef = [84.73, 119.3, 0.0]

# TODO: Check if parameters are correct
[cf21B_500]
acc_coef = 0.0
cmd_f_coef = 0.98323027
rpy_coef = [-99.94, -130.3, 0.0]
rpy_rates_coef = [-13.3, -16.33, 0.0]
cmd_rpy_coef = [84.73, 119.3, 0.0]
