name: Testing 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-1' # any version from https://github.com/mamba-org/micromamba-releases
          environment-name: test-env
          init-shell: bash
          create-args: python=3.11
      - name: Install dependencies and package
        run: pip install .[test]
        shell: micromamba-shell {0}
      - name: Test with pytest
        run: pytest tests
        shell: micromamba-shell {0}